WebMVC/Models/Genres/EditGenreViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebMVC.Models;

public class EditGenreViewModel
{
    [MinLength(1)]
    public string Name { get; set; }
}

WebMVC/Controllers/GenresController.cs
using BusinessLayer.Services.Abstraction;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Mappers;
using WebMVC.Models;

namespace WebMVC.Controllers;

[Route("genres")]
public class GenresController : Controller
{
    private readonly IGenreService _genreService;
    
    public GenresController(IGenreService genreService)
    {
        _genreService = genreService;
    }
    
    [HttpGet("{genreId:int}/edit")]
    public async Task<IActionResult> EditGenre(int genreId)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        var genreModel = await _genreService.GetGenreByIdAsync(genreId);

        if (genreModel == null)
        {
            return BadRequest($"Genre with id {genreId} does not exist");
        }
        
        return View(genreModel.MapToEditGenreViewModel());
    }
    
    [HttpPost("{genreId:int}/edit")]
    public async Task<IActionResult> EditGenre(int genreId, EditGenreViewModel model)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        var editGenreModel = model.MapToEditGenreModel();

        try
        {
            await _genreService.EditGenreAsync(genreId, editGenreModel);
        }
        catch (Exception exception)
        {
            return BadRequest(exception.Message);
        }

        return Redirect("~/");
    }
}

WebMVC/Views/Genres/EditGenre.cshtml
@using WebMVC.Models
@model EditGenreViewModel

<form method="post" asp-action="EditGenre" asp-controller="Genres">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="mt-3 btn btn-primary">Save Changes</button>
</form>