WebMVC/Components/SidebarViewComponent.cs
using BusinessLayer.Services.Abstraction;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Components;

public class SidebarViewComponent : ViewComponent
{
    private readonly IGenreService _genreService;
    private readonly IPublishersService _publisherService;
    
    public SidebarViewComponent(IGenreService genreService, IPublishersService publisherService)
    {
        _genreService = genreService;
        _publisherService = publisherService;
    }
    
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var genres = await _genreService.GetGenresAsync();
        var publishers = await _publisherService.GetPublishersAsync();
        
        var model = new SidebarViewModel
        {
            Genres = genres,
            Publishers = publishers,
        };
        
        return View(model);
    }
}

WebMVC/Controllers/BooksController.cs
using System;
using System.Diagnostics;
using BusinessLayer.Models.Book;
using BusinessLayer.Services.Abstraction;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Mappers;
using WebMVC.Models;
using WebMVC.Models.Books;
using WebMVC.Models.Review;
using BookMapper = WebMVC.Mappers.BookMapper;

namespace WebMVC.Controllers;

public class BooksController : Controller
{
    private readonly IBooksService _booksService;
    private readonly IGenreService _genresService;
    private readonly IPublishersService _publishersService;
    private readonly IReviewService _reviewService;
    private readonly UserManager<User> _userManager;


    public BooksController(IBooksService booksService,
        IGenreService genresService,
        IPublishersService publishersService,
        IReviewService reviewService,
        UserManager<User> userManager)
    {
        _booksService = booksService;
        _genresService = genresService;
        _publishersService = publishersService;
        _reviewService = reviewService;
        _userManager = userManager;
    }


    [Route("")]
    [Route("books")]
    public async Task<ActionResult> List([FromQuery] int? genreId, [FromQuery] int? publisherId, string? searchString, [FromQuery] int? pageIndex = 1, [FromQuery] int? pageSize = 10)
    {
        var books = await _booksService.GetBooksAsync(new GetBooksModel
        {
            GenreId = genreId,
            PublisherId = publisherId,
            Page = pageIndex - 1,
            PageSize = pageSize,
            Name = searchString,
        });
        var bookModels = books.Books.Select(BookMapper.MapToBookViewModel).ToList();

        var genre = genreId is null ? null : await _genresService.GetGenreByIdAsync(genreId.Value);
        var publisher = publisherId is null ? null : await _publishersService.GetPublisherByIdAsync(publisherId.Value);
        
        var foundGenres = searchString is null ? null : await _genresService.GetGenresAsync(searchString);
        var foundPublishers = searchString is null ? null : await _publishersService.GetPublishersAsync(searchString);
        var pageCount = books.TotalCount % pageSize == 0 ? books.TotalCount / pageSize : (books.TotalCount / pageSize) + 1;

        var model = new ListBooksViewModel
        {
            Books = bookModels,
            FilteredGenreName = genre?.Name,
            FilteredPublisherName = publisher?.Name,
            FoundGenres = foundGenres,
            FoundPublishers = foundPublishers,
            PageCount = (int)Math.Round((decimal)pageCount),
            PageIndex = books.PageIndex,
            PageSize = (int)pageSize,
            GenreId = genreId,
            PublisherId = publisherId,
            SearchString = searchString
        };

        return View(model);
    }

    [Route("books/{bookId:int}")]
    public async Task<ActionResult> Detail(int bookId)
    {
        var book = await _booksService.GetBookAsync(bookId);

        if (book is null)
        {
            return NotFound();
        }

        var bookModel = book.MapToBookViewModel();
        var reviews = await _reviewService.GetReviewsOfBookAsync(bookId);
        if (reviews.Count > 0)
        {
            bookModel.Reviews = reviews.MapToReviewViewModelList();
        }
        var combinedModel = new CombinedBookReviewViewModel();
        combinedModel.BookViewModel = bookModel;
        if (User.Identity?.IsAuthenticated ?? false)
        {
            var createReviewModel = new CreateReviewViewModel();
            createReviewModel.BookId = bookId;
            var user = await _userManager.FindByNameAsync(User.Identity?.Name);
            createReviewModel.UserId = user.Id;
            combinedModel.CreateReviewViewModel = createReviewModel;
        }         
        
        return View(combinedModel);
    }
    
    [HttpGet("books/{bookId:int}/edit")]
    public async Task<IActionResult> EditBook(int bookId)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        var bookModel = await _booksService.GetBookAsync(bookId);

        if (bookModel == null)
        {
            return BadRequest($"Book with id {bookId} does not exist");
        }
        
        return View(bookModel.MapToEditBookViewModel());
    }
    
    [HttpPost("books/{bookId:int}/edit")]
    public async Task<IActionResult> EditBook(int bookId, EditBookViewModel model)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        var editBookModel = model.MapToEditBookModel();

        try
        {
            await _booksService.EditBookAsync(bookId, editBookModel);
        }
        catch (Exception exception)
        {
            return BadRequest(exception.Message);
        }

        return Redirect("~/");
    }
}

WebMVC/Controllers/OrdersController.cs
using BusinessLayer.Facades;
using BusinessLayer.Models.Order;
using BusinessLayer.Services.Abstraction;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Mappers;
using WebMVC.Models;
using WebMVC.Models.Orders;

namespace WebMVC.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderFacade _orderFacade;
        private readonly IOrdersService _orderService;
        private readonly UserManager<User> _userManager;

        public OrdersController(IOrdersService orderService, UserManager<User> userManager, IOrderFacade orderFacade)
        {
            _orderService = orderService;
            _userManager = userManager;
            _orderFacade = orderFacade;
        }

        [HttpGet("orders/history")]
        public async Task<IActionResult> OrdersHistory()
        {
            var username = User.Identity?.Name;
            if (username == null)
            {
                return BadRequest("Cannot show user history, no user is logged in.");
            }
            var user = await _userManager.FindByNameAsync(username);
            if (user == null)
            {
                ViewData["ErrorMessage"] = "An error occured while loading orders history";
                return View("ErrorMessage");
            }
            
            var orders = await _orderService.GetOrdersByUserId(user.Id);
            if (orders == null)
            {
                ViewData["ErrorMessage"] = "An error occured while loading orders history";
                return View("ErrorMessage");
            }
            
            List<OrdersHistoryViewModel> ordersHistory = orders.Select(order => new OrdersHistoryViewModel()
            {
                Id = order.Id,
                TotalPrice = order.TotalPrice,
                Timestamp = order.Timestamp,
                State = order.State,
                Books = order.Books
            }).ToList();
            return View(ordersHistory);
        }

        [HttpGet("orders/edit")]
        public async Task<IActionResult> EditOrders()
        {
            if (!User.IsInRole("Admin"))
            {
                return Unauthorized();
            }

            var orders = await _orderService.GetAllOrders();
            return View(new EditOrdersViewModel()
            {
                Orders = orders.MapToOrderViewModelCollection()
            });
        }

        [HttpGet("orders/{orderId:int}/edit")]
        public async Task<IActionResult> EditOrder(int orderId)
        {
            if (!User.IsInRole("Admin"))
            {
                return Unauthorized();
            }

            var orderModel = await _orderService.GetOrder(orderId);

            if (orderModel == null)
            {
                ViewData["ErrorMessage"] = "An error occured while editing order";
                return View("ErrorMessage");
            }

            return View(orderModel.MapToEditOrderViewModel());
        }

        [HttpPost("orders/{orderId:int}/edit")]
        public async Task<IActionResult> EditOrder(int orderId, EditOrderViewModel model)
        {
            if (!User.IsInRole("Admin"))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var editOrderModel = model.MapToEditOrderModel();

            var result = await _orderService.EditOrder(orderId, editOrderModel);

            if (!result)
            {
                return BadRequest();
            }

            return RedirectToAction("EditOrders");
        }

        [HttpGet("orders/create")]
        public async Task<IActionResult> CreateOrder()
        {
            var user = await GetLoggedInUser();
            if (user == null)
            {
                return BadRequest("Cannot create new order when no user is logged in.");
            }
            
            var createOrderViewModel = new CreateOrderViewModel()
            {
                Email = user.Email ?? "",
                Address = "",
                Phone = 420,
            };
            return View(createOrderViewModel);
        }

        [HttpPost("orders/create")]
        public async Task<IActionResult> CreateOrder(CreateOrderViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await GetLoggedInUser();
            if (user == null)
            {
                return BadRequest("Order cannot be created, no user is logged in.");
            }
            
            var createOrderModel = new CreateOrderModel()
            {
                Email = model.Email,
                Address = model.Address,
                Phone = model.Phone,
                State = OrderState.Ordered,
                CartId = user.CartId,
                UserId = user.Id
            };

            try
            {
                await _orderFacade.CreateOrder(createOrderModel);
            }
            catch (Exception e)
            {
                ViewData["ErrorMessage"] = "An error occured while creating order";
                return View("ErrorMessage");
            }
            
            return RedirectToAction("OrdersHistory");
        }
        
        private async Task<User?> GetLoggedInUser()
        {
            var username = User.Identity?.Name;
            if (username == null)
            {
                return null;
            }
        
            var user = await _userManager.FindByNameAsync(username);
            return user;
        }
    }
}

WebMVC/Views/Shared/ErrorMessage.cshtml
@{
    var errorMessage = ViewData["ErrorMessage"];
}

<h2 class="text-danger">@errorMessage</h2>

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BookHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">BookHub</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <form class="d-flex gap-1" asp-action="List" asp-controller="Books" method="get">
                    <input type="text" placeholder="Search" name="searchString" /> 
                    <button type="submit" class="btn btn-outline-primary">🔍</button>
                </form>
                <ul class="navbar-nav ms-auto">
                    @if (User.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item my-auto">
                            @User.Identity.Name
                        </li>
                        <li class="nav-item my-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Cart">My cart</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="EditOrders">Edit Orders</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="OrdersHistory">My Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>


<div class="d-flex">
    @await Component.InvokeAsync("Sidebar")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - BookHub
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>