WebMVC/Models/Publishers/EditPublisherViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebMVC.Models.Publishers;

public class EditPublisherViewModel
{
    [MinLength(1)]
    public string? Name { get; set; }
    
    [MinLength(1)]
    public string? Description { get; set; }
}

WebMVC/Controllers/PublishersController.cs
using BusinessLayer.Services.Abstraction;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Mappers;
using WebMVC.Models;
using WebMVC.Models.Publishers;

namespace WebMVC.Controllers;

[Route("publishers")]
public class PublishersController : Controller
{
    private readonly IPublishersService _publishersService;
    
    public PublishersController(IPublishersService publishersService)
    {
        _publishersService = publishersService;
    }
    
    [HttpGet("{publisherId:int}/edit")]
    public async Task<IActionResult> EditPublisher(int publisherId)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        var publisherModel = await _publishersService.GetPublisherByIdAsync(publisherId);

        if (publisherModel == null)
        {
            return BadRequest($"Publisher with id {publisherId} does not exist");
        }
        
        return View(publisherModel.MapToEditPublisherViewModel());
    }
    
    [HttpPost("{publisherId:int}/edit")]
    public async Task<IActionResult> EditPublisher(int publisherId, EditPublisherViewModel model)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        var editPublisherModel = model.MapToEditPublisherModel();

        try
        {
            await _publishersService.EditPublisherAsync(publisherId, editPublisherModel);
        }
        catch (Exception exception)
        {
            return BadRequest(exception.Message);
        }

        return Redirect("~/");
    }
}

WebMVC/Views/Publishers/EditPublisher.cshtml
@using WebMVC.Models.Publishers
@model EditPublisherViewModel

<form method="post" asp-action="EditPublisher" asp-controller="Publishers">
    <div class="d-flex flex-column gap-3">
        <div class="form-group">
            <label asp-for="Name">Name:</label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description">Description:</label>
            <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    <button type="submit" class="mt-3 btn btn-primary">Save Changes</button>
</form>