WebMVC/Models/Books/BookViewModel.cs
using DataAccessLayer.Models;
using WebMVC.Models.Review;

namespace WebMVC.Models;

public class BookViewModel
{
    public int Id { get; set; }
    public string Isbn { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Count { get; set; }
    public decimal Price { get; set; }
    public List<string> Authors { get; set; }
    public List<string> Genres { get; set; }
    public string PrimaryGenre { get; set; }
    public string Publisher { get; set; }
    public List<ReviewViewModel> Reviews { get; set; }
}

WebMVC/Models/Books/CombinedBookReviewViewModel.cs
using WebMVC.Models.Review;

namespace WebMVC.Models.Books
{
    public class CombinedBookReviewViewModel
    {
        public BookViewModel? BookViewModel { get; set; }
        public CreateReviewViewModel? CreateReviewViewModel { get; set; }
    }
}

WebMVC/Models/Books/EditBookViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebMVC.Attributes;

namespace WebMVC.Models;

public class EditBookViewModel
{
    public string? Isbn { get; set; }
    
    [MinLength(1)]
    public string? Name { get; set; }
    
    [MinLength(1)]
    public string? Description { get; set; }
    
    [NonNegativeNumber(ErrorMessage = "Count must be a non-negative number.")]
    public int? Count { get; set; }
    
    [NonNegativeNumber(ErrorMessage = "Price must be a non-negative number.")]
    public decimal? Price { get; set; }
}

WebMVC/Models/Books/ListBooksViewModel.cs
using BusinessLayer.Models.Genre;
using BusinessLayer.Models.Publisher;

namespace WebMVC.Models.Books;

public class ListBooksViewModel
{
    public required ICollection<BookViewModel> Books { get; set; }
    public string? FilteredGenreName { get; set; }
    public string? FilteredPublisherName { get; set; }
    public ICollection<GenreModel>? FoundGenres { get; set; }
    public ICollection<PublisherModel>? FoundPublishers { get; set; }
    public int PageCount { get; set; }
    public int PageIndex { get; set; }
    public int PageSize { get; set; }
    public int? GenreId { get; set; }
    public int? PublisherId { get; set; }
    public String? SearchString { get; set; }
}

WebMVC/Controllers/BooksController.cs
using System;
using System.Diagnostics;
using BusinessLayer.Models.Book;
using BusinessLayer.Services.Abstraction;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Mappers;
using WebMVC.Models;
using WebMVC.Models.Books;
using WebMVC.Models.Review;
using BookMapper = WebMVC.Mappers.BookMapper;

namespace WebMVC.Controllers;

public class BooksController : Controller
{
    private readonly IBooksService _booksService;
    private readonly IGenreService _genresService;
    private readonly IPublishersService _publishersService;
    private readonly IReviewService _reviewService;
    private readonly UserManager<User> _userManager;


    public BooksController(IBooksService booksService,
        IGenreService genresService,
        IPublishersService publishersService,
        IReviewService reviewService,
        UserManager<User> userManager)
    {
        _booksService = booksService;
        _genresService = genresService;
        _publishersService = publishersService;
        _reviewService = reviewService;
        _userManager = userManager;
    }


    [Route("")]
    [Route("books")]
    public async Task<ActionResult> List([FromQuery] int? genreId, [FromQuery] int? publisherId, string? searchString, [FromQuery] int? pageIndex = 1, [FromQuery] int? pageSize = 10)
    {
        var books = await _booksService.GetBooksAsync(new GetBooksModel
        {
            GenreId = genreId,
            PublisherId = publisherId,
            Page = pageIndex - 1,
            PageSize = pageSize,
            Name = searchString,
        });
        var bookModels = books.Books.Select(BookMapper.MapToBookViewModel).ToList();

        var genre = genreId is null ? null : await _genresService.GetGenreByIdAsync(genreId.Value);
        var publisher = publisherId is null ? null : await _publishersService.GetPublisherByIdAsync(publisherId.Value);
        
        var foundGenres = searchString is null ? null : await _genresService.GetGenresAsync(searchString);
        var foundPublishers = searchString is null ? null : await _publishersService.GetPublishersAsync(searchString);
        var pageCount = books.TotalCount % pageSize == 0 ? books.TotalCount / pageSize : (books.TotalCount / pageSize) + 1;

        var model = new ListBooksViewModel
        {
            Books = bookModels,
            FilteredGenreName = genre?.Name,
            FilteredPublisherName = publisher?.Name,
            FoundGenres = foundGenres,
            FoundPublishers = foundPublishers,
            PageCount = (int)Math.Round((decimal)pageCount),
            PageIndex = books.PageIndex,
            PageSize = (int)pageSize,
            GenreId = genreId,
            PublisherId = publisherId,
            SearchString = searchString
        };

        return View(model);
    }

    [Route("books/{bookId:int}")]
    public async Task<ActionResult> Detail(int bookId)
    {
        var book = await _booksService.GetBookAsync(bookId);

        if (book is null)
        {
            return NotFound();
        }

        var bookModel = book.MapToBookViewModel();
        var reviews = await _reviewService.GetReviewsOfBookAsync(bookId);
        if (reviews.Count > 0)
        {
            bookModel.Reviews = reviews.MapToReviewViewModelList();
        }
        var combinedModel = new CombinedBookReviewViewModel();
        combinedModel.BookViewModel = bookModel;
        if (User.Identity?.IsAuthenticated ?? false)
        {
            var createReviewModel = new CreateReviewViewModel();
            createReviewModel.BookId = bookId;
            var user = await _userManager.FindByNameAsync(User.Identity?.Name);
            createReviewModel.UserId = user.Id;
            combinedModel.CreateReviewViewModel = createReviewModel;
        }         
        
        return View(combinedModel);
    }
    
    [HttpGet("books/{bookId:int}/edit")]
    public async Task<IActionResult> EditBook(int bookId)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        var bookModel = await _booksService.GetBookAsync(bookId);

        if (bookModel == null)
        {
            return BadRequest($"Book with id {bookId} does not exist");
        }
        
        return View(bookModel.MapToEditBookViewModel());
    }
    
    [HttpPost("books/{bookId:int}/edit")]
    public async Task<IActionResult> EditBook(int bookId, EditBookViewModel model)
    {
        if (!User.IsInRole("Admin"))
        {
            return Unauthorized();
        }
        
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        var editBookModel = model.MapToEditBookModel();

        try
        {
            await _booksService.EditBookAsync(bookId, editBookModel);
        }
        catch (Exception exception)
        {
            return BadRequest(exception.Message);
        }

        return Redirect("~/");
    }
}

WebMVC/Controllers/ReviewsController.cs
using BusinessLayer.Services.Abstraction;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Mappers;
using WebMVC.Models.Books;
using WebMVC.Models.Review;

namespace WebMVC.Controllers
{
    [Route("reviews")]
    public class ReviewsController : Controller
    {
        private readonly IReviewService _reviewService;

        public ReviewsController(IReviewService reviewService)
        {
            _reviewService = reviewService;
        }


        [HttpPost]
        public async Task<IActionResult> CreateReview(CombinedBookReviewViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var editReviewModel = model.CreateReviewViewModel.MapToCreateReviewModel();

            try
            {
                await _reviewService.CreateReviewAsync(editReviewModel);
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }

            return Redirect("/books/" + model.CreateReviewViewModel.BookId);
        }

        [HttpGet("{reviewId:int}/edit")]
        public async Task<IActionResult> EditReview(int reviewId)
        {
            var genreModel = await _reviewService.GetReviewByIdAsync(reviewId);

            if (genreModel == null)
            {
                return BadRequest($"Review with id {reviewId} does not exist");
            }

            return View(genreModel.MapToEditReviewViewModel());
        }

        [HttpPost("{reviewId:int}/edit")]
        public async Task<IActionResult> EditReview(int reviewId, EditReviewViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var editReviewModel = model.MapToEditReviewModel();

            try
            {
                await _reviewService.EditReviewAsync(reviewId, editReviewModel);
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }

            return Redirect($"{Request.Path.ToString()}{Request.QueryString.Value.ToString()}");
        }

        [HttpPost("delete")]
        public async Task<IActionResult> DeleteReview(int reviewId)
        {
            try
            {
                await _reviewService.DeleteReviewAsync(reviewId);
            }
            catch (Exception exception)
            {
                return BadRequest(exception.Message);
            }

            return Redirect("~/");
        }
    }
}

WebMVC/Views/Books/Detail.cshtml
@using WebMVC.Models.Books;
@model CombinedBookReviewViewModel
@{
    ViewBag.Title = Model.BookViewModel.Name;
    Layout = "_Layout";
}

<h2>📘 @Model.BookViewModel.Name</h2>
<div class="d-flex">
    <div class="d-flex flex-column gap-3">
        <div>
            <b>Authors:</b>
            <ul>
                @{
                    foreach (var author in Model.BookViewModel.Authors)
                    {
                        <li>@author</li>
                    }
                }
            </ul>
        </div>

        <div>
            <b>Primary Genre:</b> @Model.BookViewModel.PrimaryGenre
        </div>

        <div>
            <b>Genres:</b>
            <ul>
                @{
                    foreach (var genre in Model.BookViewModel.Genres)
                    {
                        <li>@genre</li>
                    }
                }
            </ul>
        </div>


        <div>
            <b>Publisher:</b> @Model.BookViewModel.Publisher
        </div>

        <div>
            <b>ISBN:</b> @Model.BookViewModel.Isbn
        </div>

        <div>
            <b>Description:</b>
            <p>
                @Model.BookViewModel.Description
            </p>
        </div>
    </div>

    <div class="d-flex flex-column gap-3">
        <div>
            <b>Price:</b> @Model.BookViewModel.Price €
        </div>


        <div>
            <b>In Stock:</b> @Model.BookViewModel.Count
        </div>
        
        @if (User.Identity?.IsAuthenticated ?? false)
        {
            if (Model.BookViewModel.Count > 0)
            {
                <form method="post" action="@Url.Action("AddBookToCart", "Cart", new { bookId = Model.BookViewModel.Id })">
                    <button type="submit" class="btn btn-primary">Add to Cart</button>
                </form>
            }
        }
        else
        {
            <span>Sign in to be able to add this book to cart.</span>
        }
    </div>
</div>
<div class="d-flex">
    <b>Reviews:</b>
    <ul>
        @{
            foreach (var review in Model.BookViewModel.Reviews)
            {
                <li>
                    <div>
                        <b>Rating:</b> @review.Rating
                    </div>

                    <div>
                        <b>Text:</b> @review.Text
                    </div>
                </li>
                @if ((User.Identity?.IsAuthenticated ?? false) && review.Username.Equals(User.Identity.Name))
                {
                    <a href="/reviews/@review.Id/edit" class="btn btn-primary">Edit</a>
                }
            }
        }
    </ul>
</div>

@if (User.Identity?.IsAuthenticated ?? false)
{
    <form method="post" asp-action="CreateReview" asp-controller="Reviews" >
        <div class="d-flex flex-column gap-3">
            <input type="hidden" asp-for="@Model.CreateReviewViewModel.BookId">
            <input type="hidden" asp-for="@Model.CreateReviewViewModel.UserId">
        <div class="form-group">
            <label asp-for="@Model.CreateReviewViewModel.Rating">Rating in range(0, 5):</label>
            <input asp-for="@Model.CreateReviewViewModel.Rating"/>
        </div>
        <div class="form-group">
            <label asp-for="@Model.CreateReviewViewModel.Text">Review text:</label>
            <input asp-for="@Model.CreateReviewViewModel.Text" class="form-control"/>
        </div>
        <button type="submit" class="mt-3 btn btn-primary">Add review</button>
        </div>
    </form>
}

WebMVC/Views/Books/EditBook.cshtml
@using WebMVC.Models
@model EditBookViewModel

<form method="post" asp-action="EditBook" asp-controller="Books">
    <div class="d-flex flex-column gap-3">
        <div class="form-group">
            <label asp-for="Isbn">ISBN:</label>
            <input asp-for="Isbn" class="form-control"/>
            <span asp-validation-for="Isbn" class="text-danger"></span>
        </div>
    
        <div class="form-group">
            <label asp-for="Name">Name:</label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    
        <div class="form-group">
            <label asp-for="Description">Description:</label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    
        <div class="form-group">
            <label asp-for="Count">Count:</label>
            <input asp-for="Count" class="form-control"/>
            <span asp-validation-for="Count" class="text-danger"></span>
        </div>
    
        <div class="form-group">
            <label asp-for="Price">Price:</label>
            <input asp-for="Price" class="form-control"/>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
</form>

WebMVC/Views/Books/List.cshtml
@model WebMVC.Models.Books.ListBooksViewModel

@{
    ViewBag.Title = "Books";
    Layout = "_Layout";
}

@if (Model.FoundGenres?.Count > 0)
{
    <div class="d-flex flex-wrap">
        <h2>Genres</h2>
        @foreach (var genre in Model.FoundGenres)
        {
            <a class="btn btn-outline-primary m-1" asp-controller="Books" asp-action="List" asp-route-genreId="@genre.Id">@genre.Name</a>
        }
    </div>
}

@if (Model.FoundPublishers?.Count > 0)
{
    <div class="d-flex flex-wrap">
        <h2>Publishers</h2>
        @foreach (var publisher in Model.FoundPublishers)
        {
            <a class="btn btn-outline-primary m-1" asp-controller="Books" asp-action="List" asp-route-publisherId="@publisher.Id">@publisher.Name</a>
        }
    </div>
}

<h2>Books</h2>

@if (Model.FilteredGenreName != null)
{
    <h3>Genre: @Model.FilteredGenreName</h3>
}

@if (Model.FilteredPublisherName != null)
{
    <h3>Publisher: @Model.FilteredPublisherName</h3>
}

@foreach (var book in Model.Books)
{
    <div class="card m-2">
        <div class="card-body d-flex justify-content-between">
            <div>
                <div>
                    <b class="card-title">@book.Name</b>
                    @if (User.IsInRole("Admin"))
                    {
                        <a href="/books/@book.Id/edit">✏️</a>
                    }
                </div>
                <p class="card-text">@book.Description</p>
                <a href="books/@book.Id" class="btn btn-primary">Detail</a>
            </div>
            <b class="card-text">@book.Price €</b>
        </div>
    </div>
}

@if(Model.Books.Count == 0)
{
    <p>No books found</p>
}
else {
    <div class="pagination">
    @for (int i = 1; i <= Model.PageCount; i++)
    {
        <a asp-action="List"
        asp-controller="Books"
        asp-route-genreId="@Model.GenreId"
        asp-route-publisherId="@Model.PublisherId"
        asp-route-searchString="@Model.SearchString"
        asp-route-pageIndex="@i"
        asp-route-pageSize="@Model.PageSize"
        class="@(i == Model.PageIndex ? "active" : "")">@($" {i}, ")</a>
    }
</div>
}